ALTER TABLE `Store`
  ADD COLUMN `isOpen` BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN `operatingHours` JSON NULL,
  ADD COLUMN `deliveryFee` DECIMAL(10,2) NOT NULL DEFAULT 0.00;

ALTER TABLE `Order`
  ADD COLUMN `deliveryFee` DECIMAL(10,2) NOT NULL DEFAULT 0.00;
